name = "discord-rpc"
version = "0.1.0"
authors = ["Adam Spofford <pieflavor.mc@gmail.com>"]
description = "the discord rich presence api"
license = "MIT"

[dependencies]
libc = "0.2"
lazy_static = "0.2"

[dependencies.discord-rpc-sys]
path = "discord-rpc-sys"
